version: 1.0.{build}

branches:
  only:
    - rtc-115992-20211124
skip_tags: true

cache:
  - C:\strawberry -> appveyor.yml

install:
  - if not exist "C:\strawberry" cinst strawberryperl
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - cpanm --installdeps .

build_script:
  - perl Build.PL
  - ./Build

test_script:
  - ./Build test

notifications:
  - provider: Email
    to:
    - jkeenan@cpan.org
    on_build_status_changed: true

